### PR TITLE
Base instances

### LINKED ISSUE #183: Define (terminal) Carrier instances for common monads?
E.g.:

```haskell
instance Carrier (Reader r) ((->) r) where …
instance Carrier (Error e) (Either e) where …
instance Carrier NonDet [] where …
instance Carrier NonDet Maybe where …
```

**Pro:**

These would make it _extremely_ convenient to e.g. use `Error` effects in pure code.

**Con:**

We can only define one `Carrier` instance per monad, so we couldn’t also define e.g. `Carrier Fail (Either String)`. This could limit the usefulness of these instances?

**Alt:**

1. We could define tiny `newtype` helpers for these tasks, e.g.:

    ```haskell
    newtype EitherC e a = EitherC { runEitherC :: Either e a }
      deriving …
    instance Carrier (Error e) (EitherC e) where …
    
    foo :: Either A B
    foo = runEitherC $ … `catchError` \ e -> …
    ```

    These would give us essentially the same interface, just with the `newtype` wrapper around the result monad.

2. We could define simple wrappers using our extant carriers, e.g.:

    ```haskell
    runEither :: ErrorC e PureC a -> Either e a
    runEither = run . runError
    ```

    AFAICS this would be equivalent to the above and should still let us `coerce` the carrier all the way to the result monad, i.e. we should also be able to define `runEither = coerce`.

### PR DESCRIPTION
**Pull request by robrix**
This PR builds on #204 to define `Carrier` instances for various `base` types, like `Either`, `(->)`, and `Maybe`.

- [x] Fixes #183.
- [x] Depends on #196.
- [x] Depends on #197.
- [x] Depends on #198.
- [x] Depends on #199.
- [x] Depends on #200.
- [x] Depends on #204.
- [x] Depends on #205.
- [x] Depends on #219.

### CODE REVIEW

File: src/Control/Carrier/Class.hs [hunk 1]
```diff
@@ -1,11 +1,40 @@
...
 ) where
 
 import Control.Effect.Class
+import Control.Effect.Choose (Choose(..))
+import Control.Effect.Empty (Empty(..))
+import Control.Effect.Error (Error(..))
+import Control.Effect.NonDet (NonDet)
+import Control.Effect.Reader (Reader(..))
+import Control.Effect.Sum ((:+:)(..))
+import Control.Effect.Writer (Writer(..))
```
Comment (robrix) [inline src/Control/Carrier/Class.hs]: The payoff: we can import all of these effect modules right where we define the `Carrier` class.

File: src/Control/Carrier/Class.hs [hunk 2]
```diff
@@ -1,11 +1,40 @@
...
+import Control.Monad ((<=<))
 
 -- | The class of carriers (results) for algebras (effect handlers) over signatures (effects), whose actions are given by the 'eff' method.
 class (HFunctor sig, Monad m) => Carrier sig m | m -> sig where
   -- | Construct a value in the carrier for an effect signature (typically a sum of a handled effect and any remaining effects).
   eff :: sig m a -> m a
+
+
+instance Carrier Empty Maybe where
+  eff Empty = Nothing
```
Comment (robrix) [inline src/Control/Carrier/Class.hs]: And that in turn allows us to implement `Carrier` instances for these effects without them being orphaned.

File: src/Control/Carrier/Class.hs [hunk 3]
```diff
@@ -1,11 +1,40 @@
...
+
+instance Carrier (Error e) (Either e) where
+  eff (Throw e)     = Left e
+  eff (Catch m h k) = either (k <=< h) k m
```
Comment (robrix) [inline src/Control/Carrier/Class.hs]: I called this branch `base-instances` both because they’re instances for types exported from `base`—`Prelude`, even!—and because, like `PureC` and `LiftC`, they’re usable as the _base_ of an effectful context. The signature does not mention `:+:`, since they’re not monad transformers.

File: src/Control/Carrier/Class.hs [hunk 4]
```diff
@@ -1,11 +1,40 @@
...
+
+instance Carrier (Reader r) ((->) r) where
+  eff (Ask       k) r = k r r
+  eff (Local f m k) r = k (m (f r)) r
```
Comment (robrix) [inline src/Control/Carrier/Class.hs]: This allows you to use these instances anywhere expecting the type in question:

```haskell
id' :: a -> a
id' = ask
```

Well, _almost_ anywhere. I can’t figure out how to make this instance available to e.g. `Control.Effect.Reader`, and I suspect it’s due to some problem with the `.hs-boot` files. But this function compiles in this module, at least.

File: src/Control/Carrier/Class.hs-boot [hunk 5]
```diff
@@ -0,0 +1,9 @@
+{-# LANGUAGE FunctionalDependencies #-}
+module Control.Carrier.Class
+( Carrier(..)
+) where
+
+import Control.Effect.Class
```
Comment (robrix) [inline src/Control/Carrier/Class.hs-boot]: In an effort to fix the aforementioned problem where `Carrier (Reader r) ((->) r)` isn’t available in e.g. `Control.Effect.Reader`, I attempted to duplicate the imports and instances here in the `.hs-boot` file, but it was not successful.

File: src/Control/Effect/Choose.hs [hunk 6]
```diff
@@ -11,7 +11,7 @@ module Control.Effect.Choose
 , Choosing(..)
 ) where
 
-import Control.Carrier
+import {-# SOURCE #-} Control.Carrier
```
Comment (robrix) [inline src/Control/Effect/Choose.hs]: These directives indicate that it’s `Control.Carrier` that gets a `.hs-boot` file, and not, say, this module.

File: src/Control/Carrier/Class.hs (hunk 3 above)
Comment (patrickt) [reply src/Control/Carrier/Class.hs]: Ah, so that means I could have an effect stack `State s :+: Error e` and discharge it into an `Either s a` with just a `runState`?

Comment (robrix) [reply src/Control/Carrier/Class.hs]: Yep, exactly.

**Comment by robrix** [comment]
Oh, I wasn’t quite ready to merge this I don’t think! No worries, we’ll tidy things up in a follow-up PR.
