### PR TITLE
Church.Cut: Fix cutfail in higher-order positions, & MonadFix

### LINKED ISSUE #279: Cut.Church: Higher-order effects allow backtracking past cutfail
`cutfail` is supposed to prune backtracking:

```haskell
λ run (runReader () (runCutA (cutfail <|> pure 'a'))) :: String
"" 
```

but the `Carrier` instance for `CutC` doesn’t preserve that property when running the effect inside higher-order positions:

```haskell
λ run (runReader () (runCutA (local (id @()) cutfail <|> pure 'a'))) :: String
"a" 
```

### LINKED ISSUE #280: Cut.Church doesn’t obey the MonadFix/left-shrinking law
`CutC` doesn’t obey the left-shrinking law:

```haskell
λ run (runCutA (mfix $ \ _ -> (pure 'a' <|> pure 'b') >>= \ y -> case y of {'a' -> cutfail ; _ -> pure 'c'})) :: String
"" 
λ run (runCutA ((pure 'a' <|> pure 'b') >>= \ y -> mfix $ \ _ -> case y of {'a' -> cutfail ; _ -> pure 'c'})) :: String
"c" 
```

I _think_ this is a bug, and not e.g. some subtle interaction of the semantics for the two interfaces that the left-shrinking law doesn’t admit as currently phrased, but I’m not 100% sure. Either way, we should fix it, rephrase the law, or remove the `MonadFix` instance for `CutC`.

Discovered in #278.

### PR DESCRIPTION
**Pull request by robrix**
- [x] Depends on #288.
- [x] Fixes #279.
- [x] Fixes #280.

### CODE REVIEW

File: src/Control/Carrier/Cut/Church.hs [hunk 1]
```diff
@@ -92,5 +91,5 @@ instance (Algebra sig m, Effect sig) => Algebra (Cut :+: NonDet :+: sig) (CutC m
   eff (L (Call m k)) = CutC $ \ cons nil fail -> runCut (\ a as -> runCut cons as fail (k a)) nil nil m
   eff (R (L (L Empty)))      = empty
   eff (R (L (R (Choose k)))) = k True <|> k False
-  eff (R (R other))          = CutC $ \ cons nil _ -> eff (handle [()] (fmap concat . traverse runCutA) other) >>= foldr cons nil
+  eff (R (R other))          = CutC $ \ cons nil fail -> eff (handle (pure ()) (runCut (fmap . (<|>)) (pure empty) (pure cutfail)) other) >>= runCut cons nil fail
```
Comment (robrix) [inline src/Control/Carrier/Cut/Church.hs]: This trick worked out beautifully, and I intend to steal it for the other nondeterminism carriers in #286 (suitably repurposed): basically, we’re using `CutC m` as its _own_ state functor. If you’ll note, we use a very similar trick in the `MonadFix` instance, using `CutC PureC` as a representation of the fixpoint.

In both cases, this works precisely because it allows us to encode lists with soft and hard emptiness: i.e. lists differentiating between `empty` and `cutfail`. This means that we then propagate `cutfail`s through the fixpoint and higher-order actions correctly, instead of mapping them to `empty` and losing the essential information.
