### PR TITLE
Split Error into Throw & Catch effects

### LINKED ISSUE #154: Polymorphic `Fail` effect?
What do you think about making the `Fail` effect take a type variable rather than being hard-coded to `String`? (The `MonadFail` instance can be recovered with a `a ~ String` constraint).

### PR DESCRIPTION
**Pull request by robrix**
This PR explores splitting `Error` up into separate `Throw` and `Catch` effects.

- [x] Redefines `Error e` as a synonym for `Throw e :+: Catch e`.
- [x] Redefines `Fail` as a synonym for `Throw String`.
- [x] Fixes #154.

### CODE REVIEW

File: src/Control/Carrier.hs [hunk 1]
```diff
@@ -1,22 +1,31 @@
...
 
-type Has eff sig m = (Member eff sig, Carrier sig m)
+-- | @m@ is a carrier for @sig@ containing @eff@.
+--
+-- Note that if @eff@ is a sum, it will be decomposed into multiple 'Member' constraints. While this technically allows one to combine multiple unrelated effects into a single 'Has' constraint, doing so has two significant drawbacks:
+--
+-- 1. Due to [a problem with recursive type families](https://gitlab.haskell.org/ghc/ghc/issues/8095), this can lead to significantly slower compiles.
+--
+-- 2. It defeats @ghc@’s warnings for redundant constraints, and thus can lead to a proliferation of redundant constraints as code is changed.
+type Has eff sig m = (Members eff sig, Carrier sig m)
```
Comment (robrix) [inline src/Control/Carrier.hs]: We’ve had a rather nasty gotcha lurking since #219 that wasn’t discovered until now: Using a `Has` constraint with an effect defined as a sum wouldn’t allow `ghc` to solve `Member` constraints for the members of that sum. Basically, given `Member (A :+: B) sig`, `ghc` wasn’t able to deduce `Member A sig`, which is necessary for `Has A sig m` to be solved.

This remained latent because `NonDet`, the only other effect defined as a sum of other effects, is used exclusively via the `Alternative` interface—we never use `Has NonDet sig m` constraints. It surfaced now because the common pattern is to use `Error e` even when you only need `Throw e`—in no small part because it wasn’t possible to say solely `Throw e` until this PR.

The solution is to decompose the sum into a series of individual `Member` constraints. Note that this technically makes `Has` capable of expressing multiple unrelated effects in a single constraint (synonym):

```haskell
foo :: Has (Reader r :+: State i :+: Error e :+: Writer w) sig m => m ()
```

However, as documented here and on `Members`, this can cause performance problems as well as defeating warnings, so it’s best to avoid it.

File: src/Control/Effect/Catch.hs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  handle state handler (Catch m h k) = Catch (handler (m <$ state)) (handler . (<$ state) . h) (handler . fmap k)
+
+
+-- | Run a computation which can throw errors with a handler to run on error.
+--
+-- Errors thrown by the handler will escape up to the nearest enclosing 'catchError' (if any).
+-- Note that this effect does /not/ handle errors thrown from impure contexts such as IO,
+-- nor will it handle exceptions thrown from pure code. If you need to handle IO-based errors,
+-- consider if 'Control.Effect.Resource' fits your use case; if not, use 'liftIO' with
+-- 'Control.Exception.try' or use 'Control.Exception.Catch' from outside the effect invocation.
```
Comment (robrix) [inline src/Control/Effect/Catch.hs]: I’ve removed the property tests for the time being; they’re being moved in #239 anyway.

File: src/Control/Effect/Fail.hs [hunk 3]
```diff
@@ -1,18 +1,12 @@
...
+import Control.Effect.Throw
 import qualified Control.Monad.Fail as Fail
-import GHC.Generics (Generic1)
 
-newtype Fail (m :: * -> *) k = Fail String
-  deriving (Functor, Generic1)
-
-instance HFunctor Fail
-instance Effect   Fail
+type Fail = Throw String
```
Comment (robrix) [inline src/Control/Effect/Fail.hs]: There is no longer any reason for `Fail` to be distinct from `Throw`!

File: src/Control/Carrier/Throw/Either.hs [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+import Control.Monad.Fix
+import Control.Monad.IO.Class
+import Control.Monad.Trans.Class
+
+-- | Run a 'Throw' effect, returning failures in 'Left' and successful computations’ results in 'Right'.
+runThrow :: ThrowC e m a -> m (Either e a)
+runThrow = runError . runThrowC
+
+newtype ThrowC e m a = ThrowC { runThrowC :: ErrorC e m a }
+  deriving (Alternative, Applicative, Functor, Monad, Fail.MonadFail, MonadFix, MonadIO, MonadPlus, MonadTrans)
```
Comment (robrix) [inline src/Control/Carrier/Throw/Either.hs]: You can, of course, also just use `ErrorC` directly, but maybe you want to guarantee the absence of `Catch` from the signature or something.

**Comment by robrix** [comment]
I am really quite happy with how this one turned out ✨
