### PR TITLE
Non-empty nondeterminism effect

### LINKED ISSUE #186: Non-empty nondeterminism
`NonDet` only expresses nondeterminism that can fail. It might also be nice to express nondeterminism like `semigroupoids` `Alt` which _can’t_ fail, i.e. which `Choose` but not `Empty`.

### PR DESCRIPTION
**Pull request by robrix**
This PR introduces a variant of `NonDet` which lacks `Empty`, and thus can only represent branching computations terminating successfully (or never terminating at all).

- [x] Depends on #197.
- [x] Fixes #186.

### CODE REVIEW

File: src/Control/Effect/Choose.hs [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+instance Fail.MonadFail m => Fail.MonadFail (ChooseC m) where
+  fail s = lift (Fail.fail s)
+  {-# INLINE fail #-}
+
+instance MonadFix m => MonadFix (ChooseC m) where
+  mfix f = ChooseC $ \ fork leaf ->
+    mfix (runChoose (liftA2 Fork) (pure . Leaf)
+      . f . fromJust . fold (<|>) Just)
+    >>= fold fork leaf
```
Comment (robrix) [inline src/Control/Effect/Choose.hs]: Like #197, this too suffers #209. I intend to fix this in a future PR (i.e. once I have any idea how to).

File: src/Control/Effect/Choose.hs [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+data Choose m k
+  = Choose (Bool -> m k)
+  deriving (Functor, Generic1)
+
+instance HFunctor Choose
+instance Effect   Choose
+
+-- | Nondeterministically choose between two computations.
+choose :: (Carrier sig m, Member Choose sig) => m a -> m a -> m a
+choose a b = send (Choose (bool b a))
```
Comment (robrix) [inline src/Control/Effect/Choose.hs]: I didn’t want to bring in a dependency on `semigroupoids` (and all of the transitive dependencies it entails), or this might have been an `Alt` instance (tho the n² instance problem would apply to that anyway).

NB: this name conflicts with #201, but I think we might want to generalize it to a `foldMapA` function instead anyway.

File: src/Control/Effect/Choose.hs [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+
```
Comment (robrix) [inline src/Control/Effect/Choose.hs]: We could consider defining functionality like `optional` against this interface, since it doesn’t require `empty`. Likewise, possibly something like `Data.List.NonEmpty.some1`.

**Comment by robrix** [comment]
Ready for review ✨

File: src/Control/Effect/Choose.hs (hunk 3 above)
Comment (robrix) [reply src/Control/Effect/Choose.hs]: `some1` would actually require `Empty` as well! Mea culpa.

Comment (robrix) [reply src/Control/Effect/Choose.hs]: no, wait

Comment (robrix) [reply src/Control/Effect/Choose.hs]: Done! See below.

**Comment by robrix** [comment]
I’ve added `optional`, `many`, `some`, and `some1` now.

**Comment by patrickt** [comment]
Since this now exports identifiers that could clash with Prelude-defined names, should we indicate in the docs that users may want to import this module qualified?

**Comment by robrix** [comment]
> Since this now exports identifiers that could clash with Prelude-defined names

None of these names are exported by Prelude.

**Comment by robrix** [comment]
@patrickt: any objection to me merging given the above? ☝️
